[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ossdata"
version = "0.3.3"
description = "Scalable SWE datasets"
authors = [
    { name = "Mouxiang Chen", email = "cmx_1007@foxmail.com" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "datasets",
    "tqdm",
    "alibabacloud-oss-v2",
]


[project.scripts]
ossdata = "ossdata.cli:main"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]